# Generated by Django 5.0.6 on 2024-07-01 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_user_auth_no_user_groups_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
