# Generated by Django 5.0.6 on 2024-07-01 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
