# Generated by Django 5.0.6 on 2024-07-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0004_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_birth",
            new_name="birth",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_password",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
