# Generated by Django 5.0.6 on 2024-07-01 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_user_address_user_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
