# Generated by Django 5.0.6 on 2024-07-01 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
