# Generated by Django 5.0.6 on 2024-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address",
            new_name="user_address",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="birth",
            new_name="user_birth",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="user_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="user_phone",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="role",
            new_name="user_role",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default=1234, max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
