# Generated by Django 5.0.6 on 2024-07-02 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_address_user_user_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event_board",
            old_name="event_ield",
            new_name="event_contents",
        ),
        migrations.RenameField(
            model_name="event_board",
            old_name="event_hit",
            new_name="event_views",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="notice_ield",
            new_name="notice_contents",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="notice_hit",
            new_name="notice_views",
        ),
        migrations.RemoveField(
            model_name="event_board",
            name="event_rdate",
        ),
        migrations.RemoveField(
            model_name="notice_board",
            name="notice_rdate",
        ),
        migrations.AddField(
            model_name="event_board",
            name="event_wdate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="notice_board",
            name="notice_wdate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
