# Generated by Django 5.0.6 on 2024-07-03 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_event_ield_event_board_event_contents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event_board",
            old_name="board_id",
            new_name="event_id",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="board_id",
            new_name="notice_id",
        ),
        migrations.RemoveField(
            model_name="event_board",
            name="event_writer",
        ),
        migrations.RemoveField(
            model_name="notice_board",
            name="notice_writer",
        ),
    ]
