# Generated by Django 5.0.6 on 2024-07-03 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_event_board_event_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RipApi",
        ),
    ]
