# Generated by Django 5.0.6 on 2024-07-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_notice_board_beach_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_board",
            name="beach_no",
            field=models.ForeignKey(
                blank=True,
                db_column="beach_no",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.beach",
            ),
        ),
    ]
