# Generated by Django 5.0.6 on 2024-07-04 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_event_board_beach_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_detail_address",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event_board",
            name="user_no",
            field=models.ForeignKey(
                db_column="user_no",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notice_board",
            name="user_no",
            field=models.ForeignKey(
                db_column="user_no",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_address",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
