# Generated by Django 5.0.6 on 2024-07-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_user_user_detail_address_alter_event_board_user_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_board",
            name="event_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="notice_board",
            name="notice_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
