# Generated by Django 5.0.6 on 2024-07-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_event_board_event_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                ("scenario_id", models.AutoField(primary_key=True, serialize=False)),
                ("scenario_code", models.CharField(max_length=20)),
                ("scenario_time", models.DateTimeField()),
                ("scenario_situation", models.TextField()),
                ("scenario_process", models.TextField()),
                ("scenario_goals", models.TextField()),
            ],
            options={
                "db_table": "scenario",
            },
        ),
        migrations.AddField(
            model_name="beach",
            name="beach_lat",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beach",
            name="beach_lon",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
