# Generated by Django 5.0.6 on 2024-07-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_beach_beach_widget_id_beach_nx_beach_ny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_board",
            name="beach_no",
            field=models.ForeignKey(
                blank=True,
                db_column="beach_no",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.beach",
            ),
        ),
        migrations.AlterField(
            model_name="notice_board",
            name="beach_no",
            field=models.ForeignKey(
                blank=True,
                db_column="beach_no",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.beach",
            ),
        ),
    ]
