# Generated by Django 5.0.6 on 2024-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_event_board_beach_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beach",
            name="mae",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beach",
            name="mse",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beach",
            name="r2score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
