# Generated by Django 5.0.6 on 2024-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_message_beach_beach_api_code_beach_mae_beach_mse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chatlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
