# Generated by Django 5.0.6 on 2024-07-16 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_chatlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.TextField(verbose_name="division")),
                ("answer", models.TextField(verbose_name="answer")),
            ],
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="answer",
            field=models.TextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="question",
            field=models.TextField(verbose_name="Question"),
        ),
    ]
