# Generated by Django 5.0.6 on 2024-07-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_database_fileupload_alter_chatlog_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="scenario_qa",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
