# Generated by Django 5.0.6 on 2024-07-21 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_beach_beach_api_code_beach_mae_beach_mse_and_more"),
        ("main", "0023_scenario_scenario_qa"),
    ]

    operations = []
