name: Django CI

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements_v1.txt

    - name: Run migrations
      run: |
        source venv/bin/activate
        python manage.py makemigrations
        python manage.py migrate

    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

                scp -r . $USER@$HOST:/path/to/your/project
                ssh $USER@$HOST <<EOF
                  cd /path/to/your/project
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install -r requirements_v1.txt
                  python manage.py makemigrations
                  python manage.py migrate
                  sudo systemctl restart gunicorn
                EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
